### PR TITLE
use absolute links in README

### LINKED ISSUE #6: Make README Markdown links point directly to GitHub pages
Look through the `README.md` file.

Change all links to files to point to their respective pages on this GitHub repository's `master` branch. For example, this:

```markdown
[link text](CODE_OF_CONDUCT.md)
```

Would be changed to this:

```markdown
[link text](https://github.com/bsoyka/passwd/blob/master/CODE_OF_CONDUCT.md)
```

The main reason for this is to fix the links on the [PyPI page](https://pypi.org/project/passwd/).

### PR DESCRIPTION
**Pull request by morrme**
Fixes #6

### CODE REVIEW

**Comment by bsoyka** [comment]
@all-contributors please add @morrme for docs

**Comment by bsoyka** [comment]
@morrme Thanks for taking the time out of your day to contribute! I won’t be making a release out of this on its own as it’s just a docs change, but you’ve been added as a contributor in the README and your changes will be put on PyPI in the next release. Have a great day/night!

**Comment by morrme** [comment]
I am happy to help! Thanks for the acknowledgement!

**Comment by bsoyka** [comment]
All contributors count, even the ones that don't push code!

**Pull request merged**
