### PR TITLE
Allow override via parameters in generate method

### LINKED ISSUE #14: Allow overriding in the PasswordGenerator class
<div align="center">
<strong>
Thanks for taking the time to contribute! 🥳
</strong>
<br><br>
<em>
Please be sure to check out our <a href="https://github.com/bsoyka/passwd/blob/master/CONTRIBUTING.md">contributing guidelines</a> and <a href="https://github.com/bsoyka/passwd/blob/master/CODE_OF_CONDUCT.md">code of conduct</a> before helping out.
</em>
</div>

---

All the properties available in the `__init__` method of the `PasswordGenerator` class should *also* be available in the `generate` method, and any arguments specified in the `generate` method should take precedence.

For example, take a look at this code:

```py
pass_gen = PasswordGenerator(8, uppercase=False, special=False)

pass_gen.generate(length=8, uppercase=True, lowercase=True)
```

In the example above, the `generate` method should end up generating a password using the values in the **Final Value** column below:

|     Argument    | Final Value | Default | `__init__` | `generate` |
|:---------------:|:-----------:|:-------:|:----------:|:----------:|
|   **`length`**  |   **`8`**   |         |     `8`    |     `8`    |
| **`uppercase`** |  **`True`** |  `True` |   `False`  |   `True`   |
| **`lowercase`** |  **`True`** |  `True` |            |   `True`   |
|   **`digits`**  |  **`True`** |  `True` |            |            |
|  **`special`**  | **`False`** |  `True` |   `False`  |            |

If you take a look at the table above, the value farthest to the right is always the final value.

The value that's given in the `generate` call should always be used first if there is one, then the value from `__init__`, then the default value.

### PR DESCRIPTION
**Pull request by echang97**
Fixes #14 
Added the following keyword args and checks:
* `length`
* `uppercase`
* `lowercase`
* `digits`
* `special`
All default to __init__ if not specified

### CODE REVIEW

**Review by bsoyka — CHANGES_REQUESTED** [review]
Fantastic! Could you add some tests for these changes?

**Comment by echang97** [comment]
What would be the best way to test it? Should I have it generate a certain number of passwords and check if they're within the constraints?

**Comment by bsoyka** [comment]
Yeah, that works! You can take a look at the existing tests in `tests/test_password_generator.py` as an example.

**Comment by bsoyka** [comment]
Fantastic! I'll go through and perform some maintenance tasks like bumping the version and testing the docs, then I'll merge this in! Thanks for your contribution!

**Pull request merged**
